# Generated by Django 4.2 on 2024-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(null=True, to='api.tag'),
        ),
    ]
