# Generated by Django 4.2 on 2024-04-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code_url',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='post',
            name='live_url',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
