# Generated by Django 4.2 on 2024-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_code_url_post_live_url_alter_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
