# Generated by Django 4.2 on 2024-04-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_description',
            field=models.TextField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_sub_title',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
