# Generated by Django 4.2 on 2024-04-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_post_email_remove_post_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_sub_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
