# Generated by Django 4.2 on 2024-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_post_post_tags_post_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_tags',
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(blank=True, null=True, to='api.tag'),
        ),
    ]
